# Generated by Django 3.0.5 on 2020-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FU', 'fundacja'), ('OP', 'organizacja pozarządowa'), ('ZL', 'zbiórka lokalna')], default='FU', max_length=2)),
                ('categories', models.ManyToManyField(to='good_hands.Category')),
            ],
        ),
    ]
