# Generated by Django 3.0.5 on 2020-05-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands', '0003_donation_is_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='is_taken',
        ),
    ]
