# Generated by Django 3.0.5 on 2020-04-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_hands', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.CharField(max_length=32),
        ),
    ]
